"""Experimental probability-aware validation and ML-style workflows.

This submodule is deliberately outside the stable package-root contract for
``0.1.0a1``.  It evaluates fitted econometric estimators and includes one
optional neural prediction challenger; it does not weaken identification
requirements or turn prediction diagnostics into econometric inference.
"""

from .adapter import ResultEligibility, infer_outcome, result_eligibility
from .bridges import (
    BridgedResult,
    BridgeProtocol,
    GenericEstimatorBridge,
    PredictProbabilityProtocol,
    PredictProtocol,
    ProbabilityBridgedResult,
    SklearnBridge,
    StatsmodelsBridge,
    generic_bridge,
    sklearn_bridge,
    statsmodels_bridge,
)
from .calibration import (
    BinaryCalibrationResult,
    BrierDecomposition,
    OrdinalCalibrationResult,
    binary_brier_decomposition,
    binary_calibration_intercept_slope,
    binary_reliability_table,
    ordinal_cumulative_calibration,
)
from .compare import ModelComparisonResult, compare_models
from .metrics import (
    binary_accuracy,
    binary_balanced_accuracy,
    binary_brier_score,
    binary_log_loss,
    binary_roc_auc,
    choice_accuracy,
    choice_brier_score,
    choice_log_loss,
    continuous_bias,
    continuous_mean_absolute_error,
    continuous_root_mean_squared_error,
    count_mean_absolute_error,
    count_root_mean_squared_error,
    duration_brier_score,
    duration_concordance_index,
    multiclass_brier_score,
    multiclass_log_loss,
    observed_outcome_rmse,
    ordinal_mean_absolute_error,
    poisson_deviance,
    quantile_check_loss,
    ranked_probability_score,
    score_predictions,
    selection_scores,
    zero_rate_calibration_error,
)
from .neural import NeuralTrainingEpoch, ResidualBinaryMLP, ResidualBinaryMLPResult
from .split import (
    EntityHoldoutSplit,
    ForwardPanelSplit,
    GroupKFold,
    GroupPanelSplit,
    KFold,
    StratifiedGroupKFold,
    StratifiedKFold,
)
from .survival import (
    CensoringDistribution,
    DynamicAUCResult,
    TimeDependentBrierResult,
    cumulative_dynamic_auc,
    fit_censoring_distribution,
    integrated_brier_score,
    ipcw_concordance_index,
    time_dependent_brier_score,
    time_dependent_brier_scores,
)
from .tuning import (
    NestedCrossValidationResult,
    NestedFoldSelection,
    TuningCandidate,
    nested_cross_validate,
)
from .uncertainty import (
    BootstrapDifference,
    OneStandardErrorSelection,
    RepeatedEntityHoldoutSplit,
    RepeatedGroupKFold,
    RepeatedKFold,
    RepeatedSplit,
    RepeatedStratifiedKFold,
    one_standard_error_select,
    paired_bootstrap_interval,
    paired_fold_score_differences,
    weighted_fold_summary,
    weighted_score_summary,
)
from .validation import CrossValidationResult, FoldEvaluation, cross_validate

__all__ = [
    "BinaryCalibrationResult",
    "BootstrapDifference",
    "BridgeProtocol",
    "BridgedResult",
    "BrierDecomposition",
    "CensoringDistribution",
    "CrossValidationResult",
    "DynamicAUCResult",
    "EntityHoldoutSplit",
    "FoldEvaluation",
    "ForwardPanelSplit",
    "GenericEstimatorBridge",
    "GroupKFold",
    "GroupPanelSplit",
    "KFold",
    "ModelComparisonResult",
    "NestedCrossValidationResult",
    "NestedFoldSelection",
    "NeuralTrainingEpoch",
    "OneStandardErrorSelection",
    "OrdinalCalibrationResult",
    "PredictProbabilityProtocol",
    "PredictProtocol",
    "ProbabilityBridgedResult",
    "RepeatedEntityHoldoutSplit",
    "RepeatedGroupKFold",
    "RepeatedKFold",
    "RepeatedSplit",
    "RepeatedStratifiedKFold",
    "ResidualBinaryMLP",
    "ResidualBinaryMLPResult",
    "ResultEligibility",
    "SklearnBridge",
    "StatsmodelsBridge",
    "StratifiedGroupKFold",
    "StratifiedKFold",
    "TimeDependentBrierResult",
    "TuningCandidate",
    "binary_accuracy",
    "binary_balanced_accuracy",
    "binary_brier_decomposition",
    "binary_brier_score",
    "binary_calibration_intercept_slope",
    "binary_log_loss",
    "binary_reliability_table",
    "binary_roc_auc",
    "choice_accuracy",
    "choice_brier_score",
    "choice_log_loss",
    "compare_models",
    "continuous_bias",
    "continuous_mean_absolute_error",
    "continuous_root_mean_squared_error",
    "count_mean_absolute_error",
    "count_root_mean_squared_error",
    "cross_validate",
    "cumulative_dynamic_auc",
    "duration_brier_score",
    "duration_concordance_index",
    "fit_censoring_distribution",
    "generic_bridge",
    "infer_outcome",
    "integrated_brier_score",
    "ipcw_concordance_index",
    "multiclass_brier_score",
    "multiclass_log_loss",
    "nested_cross_validate",
    "observed_outcome_rmse",
    "one_standard_error_select",
    "ordinal_cumulative_calibration",
    "ordinal_mean_absolute_error",
    "paired_bootstrap_interval",
    "paired_fold_score_differences",
    "poisson_deviance",
    "quantile_check_loss",
    "ranked_probability_score",
    "result_eligibility",
    "score_predictions",
    "selection_scores",
    "sklearn_bridge",
    "statsmodels_bridge",
    "time_dependent_brier_score",
    "time_dependent_brier_scores",
    "weighted_fold_summary",
    "weighted_score_summary",
    "zero_rate_calibration_error",
]
